# Bootstrap the Terraform service account — run once by a project owner.
# This creates the custom role and binds it to the SA so OpenTofu can run.
# The SA itself and its permissions are intentionally NOT managed by Terraform.

$PROJECT   = "pike-477416"
$SA        = "github-actions-terraform@$PROJECT.iam.gserviceaccount.com"
$BUCKET    = "terraform-pike-bucket-tfstate"
$ROLE_ID   = "fuel_terraform"

# Create SA if it doesn't exist
gcloud iam service-accounts create github-actions-terraform `
  --display-name "GitHub Actions Terraform" `
  --project $PROJECT 2>$null

# Create the custom role with least-privilege permissions (generated by pike)
$roleBody = @{
  title       = "Fuel Terraform"
  description = "Least-privilege role for OpenTofu CI — generated by pike"
  stage       = "GA"
  includedPermissions = @(
    "appengine.applications.get",
    "cloudscheduler.jobs.create", "cloudscheduler.jobs.delete",
    "cloudscheduler.jobs.enable", "cloudscheduler.jobs.get",
    "cloudscheduler.jobs.update",
    "datastore.databases.create", "datastore.databases.delete",
    "datastore.databases.get", "datastore.databases.getMetadata",
    "datastore.databases.update", "datastore.operations.get",
    "iam.roles.create", "iam.roles.delete", "iam.roles.get", "iam.roles.update",
    "iam.serviceAccounts.actAs",
    "iam.serviceAccounts.create", "iam.serviceAccounts.delete",
    "iam.serviceAccounts.get", "iam.serviceAccounts.getIamPolicy",
    "iam.serviceAccounts.setIamPolicy", "iam.serviceAccounts.update",
    "iam.workloadIdentityPoolProviders.create", "iam.workloadIdentityPoolProviders.delete",
    "iam.workloadIdentityPoolProviders.get", "iam.workloadIdentityPoolProviders.update",
    "iam.workloadIdentityPools.create", "iam.workloadIdentityPools.delete",
    "iam.workloadIdentityPools.get", "iam.workloadIdentityPools.getAttestationRules",
    "iam.workloadIdentityPools.update",
    "resourcemanager.projects.get", "resourcemanager.projects.getIamPolicy",
    "resourcemanager.projects.setIamPolicy",
    "run.operations.get", "run.services.create", "run.services.delete",
    "run.services.get", "run.services.getIamPolicy",
    "run.services.setIamPolicy", "run.services.update",
    "secretmanager.secrets.create", "secretmanager.secrets.delete",
    "secretmanager.secrets.get", "secretmanager.secrets.getIamPolicy",
    "secretmanager.secrets.setIamPolicy", "secretmanager.secrets.update",
    "secretmanager.versions.access", "secretmanager.versions.list",
    "serviceusage.services.disable", "serviceusage.services.enable",
    "serviceusage.services.get", "serviceusage.services.list",
    "storage.buckets.create", "storage.buckets.delete",
    "storage.buckets.get", "storage.buckets.getIamPolicy",
    "storage.buckets.list", "storage.buckets.setIamPolicy",
    "storage.buckets.update",
    "storage.objects.create", "storage.objects.delete",
    "storage.objects.get", "storage.objects.list",
    "cloudkms.keyRings.create", "cloudkms.keyRings.get", "cloudkms.keyRings.list",
    "cloudkms.cryptoKeys.create", "cloudkms.cryptoKeys.get",
    "cloudkms.cryptoKeys.list", "cloudkms.cryptoKeys.update",
    "cloudkms.cryptoKeyVersions.list",
    "cloudkms.cryptoKeys.getIamPolicy", "cloudkms.cryptoKeys.setIamPolicy"
  )
} | ConvertTo-Json -Depth 5

$tmp = New-TemporaryFile
Set-Content -Path $tmp -Value $roleBody

gcloud iam roles create $ROLE_ID --project $PROJECT --file $tmp 2>$null
if ($LASTEXITCODE -ne 0) {
    Write-Host "Role exists — updating..."
    gcloud iam roles update $ROLE_ID --project $PROJECT --file $tmp
}
Remove-Item $tmp

# Bind the custom role to the SA at project level
gcloud projects add-iam-policy-binding $PROJECT `
  --member="serviceAccount:$SA" `
  --role="projects/$PROJECT/roles/$ROLE_ID"

# Bind the custom role to the state bucket
gcloud storage buckets add-iam-policy-binding gs://$BUCKET `
  --member="serviceAccount:$SA" `
  --role="projects/$PROJECT/roles/$ROLE_ID"

# Bind WIF so GitHub Actions can impersonate the SA
$NUMBER = gcloud projects describe $PROJECT --format="value(projectNumber)"
gcloud iam service-accounts add-iam-policy-binding $SA `
  --project $PROJECT `
  --role roles/iam.workloadIdentityUser `
  --member "principalSet://iam.googleapis.com/projects/$NUMBER/locations/global/workloadIdentityPools/github-actions/attribute.repository/JamesWoolfenden/garmin-mcp-gt"

Write-Host ""
Write-Host "Done. Terraform SA is bootstrapped with least-privilege access."
