# holden:ignore:HLD_GCP_103 -- escalation-class permissions (setIamPolicy); mitigated by human-only apply, see README.md.
resource "google_project_iam_custom_role" "fuel_terraform" {
  project     = var.project_id
  role_id     = "fuel_terraform"
  title       = "Fuel Terraform"
  description = "Least-privilege role for OpenTofu CI — generated by pike"

  permissions = [
    "appengine.applications.get",
    "cloudkms.cryptoKeyVersions.destroy",
    "cloudkms.cryptoKeyVersions.list",
    "cloudkms.cryptoKeys.create",
    "cloudkms.cryptoKeys.get",
    "cloudkms.cryptoKeys.getIamPolicy",
    "cloudkms.cryptoKeys.setIamPolicy",
    "cloudkms.cryptoKeys.update",
    "cloudkms.keyRings.create",
    "cloudkms.keyRings.get",
    "cloudscheduler.jobs.create",
    "cloudscheduler.jobs.delete",
    "cloudscheduler.jobs.enable",
    "cloudscheduler.jobs.get",
    "cloudscheduler.jobs.update",
    "datastore.databases.create",
    "datastore.databases.delete",
    "datastore.databases.get",
    "datastore.databases.getMetadata",
    "datastore.databases.update",
    "datastore.operations.get",
    "iam.serviceAccounts.create",
    "iam.serviceAccounts.delete",
    "iam.serviceAccounts.get",
    "iam.serviceAccounts.getIamPolicy",
    "iam.serviceAccounts.setIamPolicy",
    "iam.serviceAccounts.update",
    "iam.workloadIdentityPoolProviders.create",
    "iam.workloadIdentityPoolProviders.delete",
    "iam.workloadIdentityPoolProviders.get",
    "iam.workloadIdentityPoolProviders.update",
    "iam.workloadIdentityPools.create",
    "iam.workloadIdentityPools.delete",
    "iam.workloadIdentityPools.get",
    "iam.workloadIdentityPools.getAttestationRules",
    "iam.workloadIdentityPools.update",
    "monitoring.uptimeCheckConfigs.create",
    "monitoring.uptimeCheckConfigs.delete",
    "monitoring.uptimeCheckConfigs.get",
    "monitoring.uptimeCheckConfigs.update",
    "resourcemanager.projects.get",
    "resourcemanager.projects.getIamPolicy",
    "resourcemanager.projects.setIamPolicy",
    "run.operations.get",
    "run.services.create",
    "run.services.delete",
    "run.services.get",
    "run.services.getIamPolicy",
    "run.services.setIamPolicy",
    "run.services.update",
    "secretmanager.secrets.create",
    "secretmanager.secrets.delete",
    "secretmanager.secrets.get",
    "secretmanager.secrets.getIamPolicy",
    "secretmanager.secrets.setIamPolicy",
    "secretmanager.secrets.update",
    "serviceusage.services.disable",
    "serviceusage.services.enable",
    "serviceusage.services.get",
    "serviceusage.services.list",
    "storage.buckets.create",
    "storage.buckets.delete",
    "storage.buckets.get",
    "storage.buckets.getIamPolicy",
    "storage.buckets.setIamPolicy",
    "storage.buckets.update"
  ]
}

# holden:ignore:HLD_GCP_059 -- same escalation risk, bound only by human apply, see README.md.
resource "google_project_iam_member" "fuel_terraform_project" {
  project = var.project_id
  role    = google_project_iam_custom_role.fuel_terraform.id
  member  = "serviceAccount:${var.terraform_sa_email}"
}

# Bucket-scoped only (HLD_GCP_555): storage.objects.* for tofu's GCS backend
# state. Bound ONLY via fuel_terraform_build_tfstate below, never at project
# level -- there's no need for this SA to read/write objects in every bucket
# in the project (e.g. terraform/sqlite.tf's CMEK bucket) just to manage the
# one tfstate bucket.
resource "google_project_iam_custom_role" "fuel_terraform_build" {
  project     = var.project_id
  role_id     = "fuel_terraform_build"
  title       = "Fuel Terraform Build"
  description = "Permissions to run the OpenTofu CI pipeline itself (GCS backend state)"

  permissions = [
    "storage.objects.create", # tofu GCS backend state (terraform/versions.tf)
    "storage.objects.delete", # tofu GCS backend state
    "storage.objects.get",    # tofu GCS backend state
    "storage.objects.list",   # tofu GCS backend state
  ]
}

# Project-scoped-only permissions (no bucket-scoped equivalent needed) that
# the CI pipeline itself uses -- kept separate from fuel_terraform_build so
# that role never needs a project-level binding. See iam/README.md.
resource "google_project_iam_custom_role" "fuel_terraform_build_metadata" {
  project     = var.project_id
  role_id     = "fuel_terraform_build_metadata"
  title       = "Fuel Terraform Build Metadata"
  description = "Project-scoped permissions the OpenTofu CI pipeline needs beyond GCS backend state"

  permissions = [
    "cloudkms.cryptoKeys.list",      # no known use
    "cloudkms.keyRings.list",        # no known use
    "secretmanager.versions.access", # ci.yml "Get internal secret" step
    "secretmanager.versions.list",   # no known use
    "storage.buckets.list",          # no known use
  ]
}

resource "google_project_iam_member" "fuel_terraform_build_metadata_project" {
  project = var.project_id
  role    = google_project_iam_custom_role.fuel_terraform_build_metadata.id
  member  = "serviceAccount:${var.terraform_sa_email}"
}

resource "google_storage_bucket_iam_member" "fuel_terraform_tfstate" {
  bucket = var.tfstate_bucket
  role   = google_project_iam_custom_role.fuel_terraform.id
  member = "serviceAccount:${var.terraform_sa_email}"
}

resource "google_storage_bucket_iam_member" "fuel_terraform_build_tfstate" {
  bucket     = var.tfstate_bucket
  role       = google_project_iam_custom_role.fuel_terraform_build.id
  member     = "serviceAccount:${var.terraform_sa_email}"
  depends_on = [time_sleep.fuel_terraform_build_propagation]
}
