# The role's permission list is additive-only relative to what's live today
# (computed via `pike compare`, see README.md): every permission currently
# granted is kept, plus the ones pike flagged as needed by terraform/ but
# missing (cloudkms.cryptoKeyVersions.destroy, monitoring.uptimeCheckConfigs.*).
#
# pike also flagged 14 currently-granted permissions as unused by the current
# IaC (iam.roles.*, iam.serviceAccounts.actAs, secretmanager.versions.*,
# storage.objects.*, and a few .list permissions) — those are deliberately
# NOT removed here. Trimming to true least-privilege is a separate, deliberate
# follow-up: some of those may be used by out-of-band steps (e.g.
# backend/setup-terraform-sa.ps1) that pike can't see since they're not
# expressed in terraform/.
resource "google_project_iam_custom_role" "fuel_terraform" {
  project     = var.project_id
  role_id     = "fuel_terraform"
  title       = "Fuel Terraform"
  description = "Least-privilege role for OpenTofu CI — generated by pike"

  permissions = [
    "appengine.applications.get",
    "cloudkms.cryptoKeyVersions.destroy",
    "cloudkms.cryptoKeyVersions.list",
    "cloudkms.cryptoKeys.create",
    "cloudkms.cryptoKeys.get",
    "cloudkms.cryptoKeys.getIamPolicy",
    "cloudkms.cryptoKeys.list",
    "cloudkms.cryptoKeys.setIamPolicy",
    "cloudkms.cryptoKeys.update",
    "cloudkms.keyRings.create",
    "cloudkms.keyRings.get",
    "cloudkms.keyRings.list",
    "cloudscheduler.jobs.create",
    "cloudscheduler.jobs.delete",
    "cloudscheduler.jobs.enable",
    "cloudscheduler.jobs.get",
    "cloudscheduler.jobs.update",
    "datastore.databases.create",
    "datastore.databases.delete",
    "datastore.databases.get",
    "datastore.databases.getMetadata",
    "datastore.databases.update",
    "datastore.operations.get",
    "iam.roles.create",
    "iam.roles.delete",
    "iam.roles.get",
    "iam.roles.update",
    "iam.serviceAccounts.actAs",
    "iam.serviceAccounts.create",
    "iam.serviceAccounts.delete",
    "iam.serviceAccounts.get",
    "iam.serviceAccounts.getIamPolicy",
    "iam.serviceAccounts.setIamPolicy",
    "iam.serviceAccounts.update",
    "iam.workloadIdentityPoolProviders.create",
    "iam.workloadIdentityPoolProviders.delete",
    "iam.workloadIdentityPoolProviders.get",
    "iam.workloadIdentityPoolProviders.update",
    "iam.workloadIdentityPools.create",
    "iam.workloadIdentityPools.delete",
    "iam.workloadIdentityPools.get",
    "iam.workloadIdentityPools.getAttestationRules",
    "iam.workloadIdentityPools.update",
    "monitoring.uptimeCheckConfigs.create",
    "monitoring.uptimeCheckConfigs.delete",
    "monitoring.uptimeCheckConfigs.get",
    "monitoring.uptimeCheckConfigs.update",
    "resourcemanager.projects.get",
    "resourcemanager.projects.getIamPolicy",
    "resourcemanager.projects.setIamPolicy",
    "run.operations.get",
    "run.services.create",
    "run.services.delete",
    "run.services.get",
    "run.services.getIamPolicy",
    "run.services.setIamPolicy",
    "run.services.update",
    "secretmanager.secrets.create",
    "secretmanager.secrets.delete",
    "secretmanager.secrets.get",
    "secretmanager.secrets.getIamPolicy",
    "secretmanager.secrets.setIamPolicy",
    "secretmanager.secrets.update",
    "secretmanager.versions.access",
    "secretmanager.versions.list",
    "serviceusage.services.disable",
    "serviceusage.services.enable",
    "serviceusage.services.get",
    "serviceusage.services.list",
    "storage.buckets.create",
    "storage.buckets.delete",
    "storage.buckets.get",
    "storage.buckets.getIamPolicy",
    "storage.buckets.list",
    "storage.buckets.setIamPolicy",
    "storage.buckets.update",
    "storage.objects.create",
    "storage.objects.delete",
    "storage.objects.get",
    "storage.objects.list",
  ]
}

# holden:ignore:HLD_GCP_059 -- this role grants iam.serviceAccounts.setIamPolicy
# and resourcemanager.projects.setIamPolicy, which pike's escalation check
# flags (holder can grant itself more access). That's exactly why this role
# definition lives in its own state, applied only by a human — never by the
# github-actions-terraform SA this role is bound to. See README.md.
resource "google_project_iam_member" "fuel_terraform_project" {
  project = var.project_id
  role    = google_project_iam_custom_role.fuel_terraform.id
  member  = "serviceAccount:${var.terraform_sa_email}"
}

resource "google_storage_bucket_iam_member" "fuel_terraform_tfstate" {
  bucket = var.tfstate_bucket
  role   = google_project_iam_custom_role.fuel_terraform.id
  member = "serviceAccount:${var.terraform_sa_email}"
}
